services:
  - type: web
    name: client-portal-management
    runtime: docker
    plan: free
    region: oregon
    branch: main
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: default
